name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv init
          uv add fastapi uvicorn streamlit transformers peft mlflow pydantic pandas scikit-learn typer datasets pytest black flake8

      - name: Check code formatting
        run: |
          black --check .
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run ETL smoke test
        run: |
          python -c "from etl.download_data import download_ag_news; download_ag_news('test_data')"
          python -c "import os; from etl.preprocess import process_ag_news; process_ag_news('test_data')"

      - name: Test API startup
        run: |
          python -c "from api.main import app; print('API startup successful')"

      - name: Test dashboard startup
        run: |
          python -c "from dashboard.app import main; print('Dashboard startup successful')"
